feat: getMatchingScore
cheminfo/mass-tools pull request #85
Opened 2022-09-27 15:06 UTC by RicardoSilvestr

2022-09-27 15:22 UTC, lpatiny requested changes

2022-09-27 15:22 UTC, lpatiny commented on package.json
> +    "ml-array-sum": "^1.1.6"
Should not be at this level.

We are not using this dependency anymore. You should use https://github.com/mljs/spectra-processing/blob/master/src/x/xSum.ts

2022-09-27 15:22 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> +const sum = require('ml-array-sum/lib/index');
Should use https://github.com/mljs/spectra-processing/blob/master/src/x/xSum.ts

2022-09-27 15:22 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> +  options = { m: 3, i: 0.6 },
Please use: massCoefficient, intensityCoefficient

2022-09-27 15:22 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> +  options = { m: 3, i: 0.6 },
You should have
`options = {}`

And at the beginning of the function
```
const {massCoefficient=3, intensityCoefficient=0.6} = options
```

2022-09-27 15:22 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> + * @param {object} [options={}] - object containing the scale factor for mass and intensity (m and i)
@param {number} [massCoefficient=3]  

same of intensityCoefficient

2022-09-27 15:22 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> +      Math.pow(matchedExpFragments.y[i], options.i) *
`matchedExpFragments.y[i] ** intensityCoefficient`

2022-09-27 15:22 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> +  return Math.round(finalScore * 1000) / 1000;
Never round number is a code. This is only a UX and should be rounded when displaying the result to the enduser.

2022-10-03 09:51 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> + * @param {number} [massCoefficient=3]
Should be [options.massCoeffcient]

2022-10-03 09:51 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> + * @param {number} [intensityCoefficient=3]
same

2022-10-03 09:53 UTC, lpatiny commented
Please check that you have all thos eoptions in your vscode settings

https://github.com/cheminfo/generator-cheminfo/blob/main/START.md

```
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "files.eol": "\n",
  "js/ts.implicitProjectConfig.checkJs": true,
```

2022-10-03 09:57 UTC, RicardoSilvestr commented
> 

I have all this options and no error appeared in the code

2022-10-03 09:57 UTC, RicardoSilvestr commented
> Please check that you have all thos eoptions in your vscode settings
> 
> https://github.com/cheminfo/generator-cheminfo/blob/main/START.md
> 
> ```
>   "editor.defaultFormatter": "esbenp.prettier-vscode",
>   "editor.formatOnSave": true,
>   "editor.codeActionsOnSave": {
>     "source.fixAll.eslint": true
>   },
>   "files.eol": "\n",
>   "js/ts.implicitProjectConfig.checkJs": true,
> ```


I have all this options and no error appeared in the code

2022-10-03 14:12 UTC, lpatiny requested changes

2022-10-03 14:12 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> +// Scaling mass and intensity power can be found in DOI: 10.1016/1044-0305(94)87009-8
You should not add comments here because there is a risk jsdoc will not be associated to the function

2022-10-03 14:12 UTC, lpatiny commented on packages/ms-spectrum/src/getMatchingScore.js
> + * Filter the array of peaks
You should add more documentation here. I still don't understand what this function does.

2022-10-03 17:47 UTC, targos commented on packages/emdb/src/util/fetchJSON.js
> +  const timeoutId = setTimeout(() => controller.abort(), 300000);
You can use `AbortSignal.timeout` instead: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout

2022-10-03 18:07 UTC, RicardoSilvestr commented
Node 12 error happens because jest does not accept the question mark operator:
```
Details:

    /home/runner/work/mass-tools/mass-tools/packages/ms-spectrum/node_modules/ml-spectra-processing/lib/matrix/matrixCreateEmpty.js:8
        const { matrix, nbRows = matrix?.length || 1, nbColumns = matrix?.[0].length || 1, ArrayConstructor = Float64Array, } = options;
                                        ^

    SyntaxError: Unexpected token '.'
```
Node 14 fails just because of AbortSignal.timeout function, otherwise it passes.

Node 16 and 18 were failing because of a DNS issue (that's what i found online) and it was just enough to restart docker and the problem was solved.

2023-09-04 09:29 UTC, closed without merging